services:
  web:
    image: web
    build:
      context: .
      dockerfile: Web/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5214:5214
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: database:5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - database
    networks:
      - app
  
  database:
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app
volumes:
  postgres_data:
    driver: local
networks:
  app:
    driver: bridge